 -- MySQL Script generated by MySQL Workbench
-- 05/23/16 05:40:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `Id` INT(11) NOT NULL COMMENT '',
  `Country` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC)  COMMENT '',
  UNIQUE INDEX `Country_UNIQUE` (`Country` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`userlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`userlog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`userlog` (
  `User_Name` VARCHAR(45) NOT NULL COMMENT '',
  `Ip_Address` VARCHAR(45) NOT NULL COMMENT '',
  `Operation` VARCHAR(45) NOT NULL COMMENT '',
  `Time` DATE NOT NULL COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `FirstName` VARCHAR(45) NOT NULL COMMENT '',
  `LastName` VARCHAR(45) NOT NULL COMMENT '',
  `Email` VARCHAR(45) NOT NULL COMMENT '',
  `Address` VARCHAR(45) NULL DEFAULT 'Amman' COMMENT '',
  `Status` INT(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`userweb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`userweb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`userweb` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `User_Name` VARCHAR(45) NOT NULL COMMENT '',
  `First_Name` VARCHAR(45) NOT NULL COMMENT '',
  `Last_Name` VARCHAR(45) NOT NULL COMMENT '',
  `Email` VARCHAR(45) NOT NULL COMMENT '',
  `Password` VARCHAR(45) NOT NULL COMMENT '',
  `Status` INT(1) NOT NULL DEFAULT '1' COMMENT '',
  `Country` VARCHAR(45) NOT NULL COMMENT '',
  `PhoneNumber` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `User_Name_UNIQUE` (`User_Name` ASC)  COMMENT '',
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure Add_Delete_UPdate_Procedure
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`Add_Delete_UPdate_Procedure`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Add_Delete_UPdate_Procedure`(in p_Type int, in p_Id int, in p_FirstName varchar(500), in p_LasttName varchar(500), in p_Email varchar(500), in p_Address varchar(500), out o_result varchar(100) )
BEGIN

IF p_Type = 1 AND p_Id=0
THEN
INSERT INTO `mydb`.`users`
(FirstName,LastName,Email,Address) VALUES (p_FirstName,p_LasttName,p_Email,p_Address);

set o_result='Insert';

ELSEIF p_Type = 2 AND p_Id >0
THEN
UPDATE `mydb`.`users`
SET FirstName = p_FirstName, LastName = p_LasttName, Email = p_Email, Address = p_Address
WHERE Id = p_Id;
set o_result='UPDATE';

ELSEIF p_Type = 3 and p_Id >0
THEN
UPDATE `mydb`.`users`
SET Status = 0
WHERE Id = p_Id;
set o_result='delete';
END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure getUsersPR
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`getUsersPR`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getUsersPR`(in p_type int, in p_id int)
BEGIN
IF p_type = 0 and p_id = 0
THEN
 SELECT `users`.`Id`,
    `users`.`FirstName`,
    `users`.`LastName`,
    `users`.`Email`,
    `users`.`Address`,
    `users`.`Status`
FROM `mydb`.`users` ORDER BY ID DESC;
ELSEIF p_type = 1 and p_id <> 0
THEN
 SELECT `users`.`Id`,
    `users`.`FirstName`,
    `users`.`LastName`,
    `users`.`Email`,
    `users`.`Address`,
    `users`.`Status`
FROM `mydb`.`users` WHERE ID = p_id;
END IF;


END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
